// Rivera Press — the site where missions begin.
import { mountBaton, newMission, round2, addDays, todayISO } from './baton.js';
import { SITE, ROUTE } from './config.js';

/* BEGIN DEMO KEY — generated by scripts/keygen.mjs on 2026-09-02.
   DEMO ONLY. In a real deployment the private key never reaches the browser:
   signing happens in a serverless function on this origin, and this file would
   call it instead of holding the key. The public half is published at
   /.well-known/baton/key.json so any other site can check our signatures. */
const DEMO_PRIVATE_JWK = {
  "kty": "EC",
  "crv": "P-256",
  "d": "4AjVoonwk9UIZRK0cYh1XcF-9oep8sXg1XTL4_zVfbw",
  "x": "UtQaA4RJxiaGb6yzNkD9ahFdg7WFj7TDDlGt1KWZQFM",
  "y": "1Qwqy6fhyqnqfKtjxqyPWgtNv3i2XUAraZ9-Ra98CHY",
  "kid": "rivera-2026-09"
};
/* END DEMO KEY */

const PAPERS = [
  { id: 'photo_rag', name: 'Hahnemühle Photo Rag 308', character: 'Cotton, matte, deep blacks', price_20x30: 9.50, price_30x40: 16.00 },
  { id: 'baryta', name: 'Canson Baryta Photographique', character: 'Semi-gloss, high contrast', price_20x30: 8.25, price_30x40: 14.00 },
  { id: 'cotton_rag', name: 'Ilford Smooth Cotton Rag', character: 'Soft matte, warm white', price_20x30: 7.00, price_30x40: 12.50 },
  { id: 'hot_press', name: 'Epson Hot Press Natural', character: 'Textured, the budget sheet', price_20x30: 6.25, price_30x40: 11.00 }
];

const SIZES = ['20x30', '30x40'];

function findPaper(q) {
  const s = String(q || '').toLowerCase().trim();
  return PAPERS.find((p) => p.id === s) ||
    PAPERS.find((p) => p.name.toLowerCase() === s) ||
    PAPERS.find((p) => p.name.toLowerCase().includes(s) || p.id.includes(s));
}

function turnaroundDays(quantity) {
  if (quantity <= 20) return 3;
  if (quantity <= 60) return 5;
  return 9;
}

/* ------------------------------------------------------------------- page */

document.getElementById('host-label').textContent = location.host || 'file://';

document.getElementById('papers').innerHTML = PAPERS.map((p) =>
  '<tr><td>' + p.name + '</td><td class="muted">' + p.character + '</td>' +
  '<td class="num">$' + p.price_20x30.toFixed(2) + '</td>' +
  '<td class="num">$' + p.price_30x40.toFixed(2) + '</td></tr>'
).join('');

const baton = mountBaton({
  ...SITE,
  route: ROUTE,
  privateJwk: DEMO_PRIVATE_JWK,
  panel: document.getElementById('mission-panel'),
  toolsBox: document.getElementById('site-tools')
});

if (!baton.hasWebMCP) document.getElementById('no-webmcp').hidden = false;

/* ------------------------------------------------------------ site tools */
/* Rivera registers its own tools always: this is where missions start. */

baton.registerAlways((signal, register) => {
  register({
    name: 'list_papers',
    description: 'The papers Rivera Press stocks, with the price of one print on each at 20x30 cm and at 30x40 cm.',
    inputSchema: { type: 'object', properties: {}, additionalProperties: false },
    annotations: { readOnlyHint: true },
    execute: async () => ({ ok: true, currency: 'USD', sizes: SIZES, papers: PAPERS })
  }, signal);

  register({
    name: 'quote_run',
    description: 'Price a print run: total, price per print, and how many days the press needs.',
    inputSchema: {
      type: 'object',
      properties: {
        quantity: { type: 'integer', description: 'How many prints.' },
        size: { type: 'string', enum: SIZES, description: 'Print size in cm.' },
        paper: { type: 'string', description: 'Paper id or name from list_papers.' }
      },
      required: ['quantity', 'size', 'paper'],
      additionalProperties: false
    },
    annotations: { readOnlyHint: true },
    execute: async (input) => {
      const paper = findPaper(input.paper);
      if (!paper) return { ok: false, error: 'no such paper', choices: PAPERS.map((p) => p.id) };
      if (!SIZES.includes(input.size)) return { ok: false, error: 'size must be 20x30 or 30x40' };
      const per = input.size === '20x30' ? paper.price_20x30 : paper.price_30x40;
      const days = turnaroundDays(input.quantity);
      return {
        ok: true,
        paper: paper.name,
        paper_id: paper.id,
        size: input.size,
        quantity: input.quantity,
        per_print_usd: per,
        total_usd: round2(per * input.quantity),
        turnaround_days: days,
        ready_on: addDays(todayISO(), days)
      };
    }
  }, signal);

  register({
    name: 'baton_start',
    description: 'Start a mission at Rivera Press. Writes the goal, the budget, the deadline and the quantity into a baton, sets the route (print here, then the bindery, then the courier), and puts it on the page so the rest of the baton tools appear.',
    inputSchema: {
      type: 'object',
      properties: {
        goal: { type: 'string', description: 'What the whole job is, in one line.' },
        budget_usd: { type: 'number', description: 'Total budget for the whole job, in US dollars.' },
        deadline: { type: 'string', description: 'Final deadline as YYYY-MM-DD.' },
        quantity: { type: 'integer', description: 'How many copies the whole job covers.' }
      },
      required: ['goal', 'budget_usd', 'deadline', 'quantity'],
      additionalProperties: false
    },
    annotations: { readOnlyHint: false },
    execute: async (input) => {
      const current = baton.mission;
      if (current && current.legs.length > 0) {
        return { ok: false, error: 'a mission with signed legs is already aboard (' + current.id + '); finish or drop it first' };
      }
      if (!/^\d{4}-\d{2}-\d{2}$/.test(String(input.deadline))) {
        return { ok: false, error: 'deadline must look like YYYY-MM-DD' };
      }
      const mission = newMission({
        goal: input.goal,
        budget_usd: input.budget_usd,
        deadline: input.deadline,
        quantity: input.quantity,
        route: ROUTE
      });
      const set = await baton.setMission(mission, { source: 'baton_start' });
      if (!set.ok) return { ok: false, error: set.reason };
      return {
        ok: true,
        mission: { id: mission.id, goal: mission.goal, constraints: mission.constraints, route: mission.route },
        note: 'The baton is on the page. The common baton tools are now registered.'
      };
    }
  }, signal);

  register({
    name: 'reserve_print_slot',
    description: 'Hold a press day at Rivera Press. Needs the operator to click Confirm on the page. Returns the booking evidence to attach to the print leg.',
    inputSchema: {
      type: 'object',
      properties: { date: { type: 'string', description: 'Press day as YYYY-MM-DD.' } },
      required: ['date'],
      additionalProperties: false
    },
    annotations: { readOnlyHint: false },
    execute: async (input, client) => {
      if (!/^\d{4}-\d{2}-\d{2}$/.test(String(input.date))) return { ok: false, error: 'date must look like YYYY-MM-DD' };
      const c = await baton.confirmInPage(client, 'Rivera Press: hold a press day on ' + input.date + '?', 'reserve_print_slot', input);
      const blocked = baton.needsConfirm(c, 'reserve_print_slot');
      if (blocked) return { ...blocked, confirm_path: c.path };
      const evidence = {
        slot_id: 'RP-' + input.date.replace(/-/g, '') + '-' + Math.random().toString(36).slice(2, 6).toUpperCase(),
        press: 'Rivera bay 2, Epson P9500',
        date: input.date,
        capacity_prints: 60,
        held_by: 'Rivera Press'
      };
      baton.debug('press slot held for ' + input.date);
      return { ok: true, evidence, confirm_path: c.path, note: 'Pass this evidence to baton_complete_leg.' };
    }
  }, signal);
});
