// Ruta Courier — takes the delivery leg, usually the last one.
import { mountBaton, round2, addDays, todayISO } from './baton.js';
import { SITE, ROUTE } from './config.js';

/* BEGIN DEMO KEY — generated by scripts/keygen.mjs on 2026-09-02.
   DEMO ONLY. In a real deployment the private key never reaches the browser:
   signing happens in a serverless function on this origin, and this file would
   call it instead of holding the key. The public half is published at
   /.well-known/baton/key.json so any other site can check our signatures. */
const DEMO_PRIVATE_JWK = {
  "kty": "EC",
  "crv": "P-256",
  "d": "jyWNsXV2PqFhb1GQuPzK5M1-J23Wx5XXgqszeu_7Vhk",
  "x": "ou_FmhZwsXhWpw2Q4p_kTrxHrUCdX2UnCUvzSxJ9XzM",
  "y": "BoWaRdbxLx2LRWSJDu4O0Gz5G0g7P4G3Id7o6umwU9A",
  "kid": "ruta-2026-09"
};
/* END DEMO KEY */

const SPEEDS = [
  { id: 'standard', name: 'Standard', transit_days: 2, base_usd: 18.00, per_copy_usd: 0.15 },
  { id: 'express', name: 'Express', transit_days: 1, base_usd: 26.00, per_copy_usd: 0.35 }
];

const ZONES = [
  { id: 'centro', name: 'Centro and the old port', cutoff: '15:00' },
  { id: 'norte', name: 'Norte industrial belt', cutoff: '13:00' },
  { id: 'valle', name: 'Valle and the two university campuses', cutoff: '12:00' }
];

/* ------------------------------------------------------------------- page */

document.getElementById('host-label').textContent = location.host || 'file://';

document.getElementById('speeds').innerHTML = SPEEDS.map((s) =>
  '<tr><td>' + s.name + '</td><td class="muted">' + s.transit_days + ' day' + (s.transit_days === 1 ? '' : 's') + '</td>' +
  '<td class="num">$' + s.base_usd.toFixed(2) + '</td><td class="num">$' + s.per_copy_usd.toFixed(2) + '</td></tr>'
).join('');

document.getElementById('zones').innerHTML = ZONES.map((z) =>
  '<tr><td>' + z.name + '</td><td class="muted">' + z.id + '</td><td class="num">' + z.cutoff + '</td></tr>'
).join('');

const baton = mountBaton({
  ...SITE,
  route: ROUTE,
  privateJwk: DEMO_PRIVATE_JWK,
  panel: document.getElementById('mission-panel'),
  toolsBox: document.getElementById('site-tools')
});

if (!baton.hasWebMCP) document.getElementById('no-webmcp').hidden = false;

// Default pickup is the day after the latest date already booked on the mission.
function defaultPickupDate() {
  const m = baton.mission;
  let latest = todayISO();
  for (const leg of m?.legs || []) {
    for (const v of Object.values(leg.evidence || {})) {
      if (typeof v === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(v) && v > latest) latest = v;
    }
  }
  return addDays(latest, 1);
}

/* ------------------------------------------- always on: one plain read tool */

baton.registerAlways((signal, register) => {
  register({
    name: 'service_areas',
    description: 'The zones Ruta Courier collects from and delivers to, with the daily collection cut-off for each.',
    inputSchema: { type: 'object', properties: {}, additionalProperties: false },
    annotations: { readOnlyHint: true },
    execute: async () => ({
      ok: true,
      zones: ZONES,
      speeds: SPEEDS.map((s) => ({ id: s.id, transit_days: s.transit_days })),
      note: 'Pricing a delivery needs a mission aboard. Arrive with a baton in the link.'
    })
  }, signal);
});

/* ------------------------------------ only when a mission is on the page */

baton.registerWhenMissionAboard((signal, register) => {
  register({
    name: 'quote_delivery_for_mission',
    description: 'Price the delivery for the quantity the mission carries and say which day it lands, given a pickup date. Also checks the cost and the delivery date against the mission constraints.',
    inputSchema: {
      type: 'object',
      properties: {
        speed: { type: 'string', enum: ['standard', 'express'], description: 'How fast it travels.' },
        pickup_date: { type: 'string', description: 'Collection day as YYYY-MM-DD. Defaults to the day after the last date already booked on the mission.' }
      },
      required: ['speed'],
      additionalProperties: false
    },
    annotations: { readOnlyHint: true },
    execute: async (input) => {
      const speed = SPEEDS.find((s) => s.id === input.speed);
      if (!speed) return { ok: false, error: 'speed must be standard or express' };
      const pickup = input.pickup_date || defaultPickupDate();
      if (!/^\d{4}-\d{2}-\d{2}$/.test(pickup)) return { ok: false, error: 'pickup_date must look like YYYY-MM-DD' };
      const qty = baton.mission.constraints.quantity;
      const cost = round2(speed.base_usd + speed.per_copy_usd * qty);
      const delivery = addDays(pickup, speed.transit_days);
      return {
        ok: true,
        speed: speed.id,
        quantity: qty,
        pickup_date: pickup,
        transit_days: speed.transit_days,
        delivery_date: delivery,
        cost_usd: cost,
        check: baton.checkAction({ cost_usd: cost, date: delivery })
      };
    }
  }, signal);

  register({
    name: 'book_collection',
    description: 'Book the van. Needs the operator to click Confirm on the page. Returns a tracking id and the delivery estimate to attach to the delivery leg.',
    inputSchema: {
      type: 'object',
      properties: { pickup_date: { type: 'string', description: 'Collection day as YYYY-MM-DD.' } },
      required: ['pickup_date'],
      additionalProperties: false
    },
    annotations: { readOnlyHint: false },
    execute: async (input, client) => {
      if (!/^\d{4}-\d{2}-\d{2}$/.test(String(input.pickup_date))) return { ok: false, error: 'pickup_date must look like YYYY-MM-DD' };
      const c = await baton.confirmInPage(client, 'Ruta Courier: book collection on ' + input.pickup_date + '?', 'book_collection', input);
      const blocked = baton.needsConfirm(c, 'book_collection');
      if (blocked) return { ...blocked, confirm_path: c.path };
      const evidence = {
        tracking_id: 'RUTA-' + Math.random().toString(36).slice(2, 8).toUpperCase(),
        pickup_date: input.pickup_date,
        delivery_estimate: addDays(input.pickup_date, 2),
        vehicle: 'Van 4',
        zone: 'norte',
        booked_by: 'Ruta Courier'
      };
      baton.debug('collection booked for ' + input.pickup_date);
      return { ok: true, evidence, confirm_path: c.path, note: 'Pass this evidence to baton_complete_leg.' };
    }
  }, signal);
});
