// Norte Bindery — takes the binding leg of a mission that arrives with a baton.
import { mountBaton, round2 } from './baton.js';
import { SITE, ROUTE } from './config.js';

/* BEGIN DEMO KEY — generated by scripts/keygen.mjs on 2026-09-02.
   DEMO ONLY. In a real deployment the private key never reaches the browser:
   signing happens in a serverless function on this origin, and this file would
   call it instead of holding the key. The public half is published at
   /.well-known/baton/key.json so any other site can check our signatures. */
const DEMO_PRIVATE_JWK = {
  "kty": "EC",
  "crv": "P-256",
  "d": "C71kb2DdbL9cGGBxLgK-MRiY_FLwbGdXgub87ZJvKCc",
  "x": "b68mN92O3Ms0abOsl80kGRopttkQ7U0zKH3msn-F0eg",
  "y": "7ZCVcQ7TKTAkTUwatVFld3AHC1LZ-RIgOQCbRI3zjFA",
  "kid": "norte-2026-09"
};
/* END DEMO KEY */

const BINDINGS = [
  { id: 'coptic', name: 'Coptic stitch, exposed spine', notes: 'Lies completely flat, three signatures', per_copy: 5.25 },
  { id: 'japanese_stab', name: 'Japanese stab binding', notes: 'Side-sewn, no spine glue, quick', per_copy: 4.25 },
  { id: 'saddle_folio', name: 'Saddle-stitched folio', notes: 'Two staples, fastest bench', per_copy: 3.10 }
];

const COVERS = [
  { id: 'cloth_board', name: 'Cloth-wrapped board', notes: 'Bookcloth over 2 mm board', per_copy: 1.25 },
  { id: 'light_card', name: 'Light card wrap', notes: '300 gsm card, scored fold', per_copy: 0.50 }
];

const byId = (list, q) => {
  const s = String(q || '').toLowerCase().trim();
  return list.find((x) => x.id === s) || list.find((x) => x.name.toLowerCase().includes(s));
};

/* ------------------------------------------------------------------- page */

document.getElementById('host-label').textContent = location.host || 'file://';

document.getElementById('bindings').innerHTML = BINDINGS.map((b) =>
  '<tr><td>' + b.name + '</td><td class="muted">' + b.notes + '</td><td class="num">$' + b.per_copy.toFixed(2) + '</td></tr>'
).join('');

document.getElementById('covers').innerHTML = COVERS.map((c) =>
  '<tr><td>' + c.name + '</td><td class="muted">' + c.notes + '</td><td class="num">$' + c.per_copy.toFixed(2) + '</td></tr>'
).join('');

const baton = mountBaton({
  ...SITE,
  route: ROUTE,
  privateJwk: DEMO_PRIVATE_JWK,
  panel: document.getElementById('mission-panel'),
  toolsBox: document.getElementById('site-tools')
});

if (!baton.hasWebMCP) document.getElementById('no-webmcp').hidden = false;

/* ------------------------------------------- always on: one plain read tool */

baton.registerAlways((signal, register) => {
  register({
    name: 'about_bindery',
    description: 'What Norte Bindery is and what it can take on: benches, capacity and the kind of work it accepts.',
    inputSchema: { type: 'object', properties: {}, additionalProperties: false },
    annotations: { readOnlyHint: true },
    execute: async () => ({
      ok: true,
      name: 'Norte Bindery',
      founded: 2011,
      benches: 2,
      capacity_copies_per_day: 120,
      takes: 'binding legs only, ten copies and up',
      note: 'Quoting a job needs a mission aboard. Arrive with a baton in the link.'
    })
  }, signal);
});

/* ------------------------------------ only when a mission is on the page */

baton.registerWhenMissionAboard((signal, register) => {
  register({
    name: 'list_bindings',
    description: 'The three binding styles Norte offers with their per-copy price, and the two cover options with theirs.',
    inputSchema: { type: 'object', properties: {}, additionalProperties: false },
    annotations: { readOnlyHint: true },
    execute: async () => ({ ok: true, currency: 'USD', bindings: BINDINGS, covers: COVERS })
  }, signal);

  register({
    name: 'quote_binding_for_mission',
    description: 'Price a binding for the quantity the mission carries, and say straight away whether the mission budget still allows it.',
    inputSchema: {
      type: 'object',
      properties: {
        binding: { type: 'string', description: 'Binding id or name from list_bindings.' },
        cover: { type: 'string', description: 'Cover id or name from list_bindings.' }
      },
      required: ['binding', 'cover'],
      additionalProperties: false
    },
    annotations: { readOnlyHint: true },
    execute: async (input) => {
      const b = byId(BINDINGS, input.binding);
      const c = byId(COVERS, input.cover);
      if (!b) return { ok: false, error: 'no such binding', choices: BINDINGS.map((x) => x.id) };
      if (!c) return { ok: false, error: 'no such cover', choices: COVERS.map((x) => x.id) };
      const qty = baton.mission.constraints.quantity;
      const per = round2(b.per_copy + c.per_copy);
      const cost = round2(per * qty);
      const check = baton.checkAction({ cost_usd: cost });
      return {
        ok: true,
        binding: b.name,
        binding_id: b.id,
        cover: c.name,
        cover_id: c.id,
        quantity: qty,
        per_copy_usd: per,
        cost_usd: cost,
        bench_days: qty <= 60 ? 2 : 4,
        check
      };
    }
  }, signal);

  register({
    name: 'reserve_press_slot',
    description: 'Hold a bench day at Norte Bindery. Needs the operator to click Confirm on the page. Returns the booking evidence to attach to the binding leg.',
    inputSchema: {
      type: 'object',
      properties: { date: { type: 'string', description: 'Bench day as YYYY-MM-DD.' } },
      required: ['date'],
      additionalProperties: false
    },
    annotations: { readOnlyHint: false },
    execute: async (input, client) => {
      if (!/^\d{4}-\d{2}-\d{2}$/.test(String(input.date))) return { ok: false, error: 'date must look like YYYY-MM-DD' };
      const c = await baton.confirmInPage(client, 'Norte Bindery: hold a bench day on ' + input.date + '?', 'reserve_press_slot', input);
      const blocked = baton.needsConfirm(c, 'reserve_press_slot');
      if (blocked) return { ...blocked, confirm_path: c.path };
      const evidence = {
        slot_id: 'NB-' + input.date.replace(/-/g, '') + '-' + Math.random().toString(36).slice(2, 6).toUpperCase(),
        bench: 'Norte bench 1',
        date: input.date,
        held_by: 'Norte Bindery'
      };
      baton.debug('bench day held for ' + input.date);
      return { ok: true, evidence, confirm_path: c.path, note: 'Pass this evidence to baton_complete_leg.' };
    }
  }, signal);
});
