#!/usr/bin/env node
// Generate one ECDSA P-256 key pair per site.
//   - the PUBLIC half goes to sites/<site>/.well-known/baton/key.json (served with CORS *)
//   - the PRIVATE half is written into sites/<site>/site.js between the DEMO KEY markers
//
// Signing in the page is fine for this v0 demo and nothing else. In a real
// deployment the private key stays in a serverless function on that origin.
//
//   node scripts/keygen.mjs          # only fills sites that have no key yet
//   node scripts/keygen.mjs --force  # regenerate everything (invalidates old signatures)

import { webcrypto } from 'node:crypto';
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const force = process.argv.includes('--force');

const SITES = [
  { dir: 'rivera-press', name: 'Rivera Press', kid: 'rivera-2026-09' },
  { dir: 'norte-bindery', name: 'Norte Bindery', kid: 'norte-2026-09' },
  { dir: 'ruta-courier', name: 'Ruta Courier', kid: 'ruta-2026-09' }
];

const BEGIN = '/* BEGIN DEMO KEY';
const END = '/* END DEMO KEY */';

for (const site of SITES) {
  const base = join(ROOT, 'sites', site.dir);
  const keyPath = join(base, '.well-known', 'baton', 'key.json');
  const sitePath = join(base, 'site.js');
  const source = readFileSync(sitePath, 'utf8');
  const alreadyKeyed = existsSync(keyPath) && !/const DEMO_PRIVATE_JWK = null;/.test(source);

  if (alreadyKeyed && !force) {
    console.log(`${site.dir}: key already in place, left alone (use --force to replace)`);
    continue;
  }

  const pair = await webcrypto.subtle.generateKey({ name: 'ECDSA', namedCurve: 'P-256' }, true, ['sign', 'verify']);
  const pub = await webcrypto.subtle.exportKey('jwk', pair.publicKey);
  const priv = await webcrypto.subtle.exportKey('jwk', pair.privateKey);

  const publicDoc = {
    kid: site.kid,
    site: site.name,
    alg: 'ES256',
    use: 'baton-leg-signature',
    created: new Date().toISOString().slice(0, 10),
    jwk: { kty: pub.kty, crv: pub.crv, x: pub.x, y: pub.y }
  };
  mkdirSync(dirname(keyPath), { recursive: true });
  writeFileSync(keyPath, JSON.stringify(publicDoc, null, 2) + '\n');

  const privateJwk = { kty: priv.kty, crv: priv.crv, d: priv.d, x: priv.x, y: priv.y, kid: site.kid };
  const start = source.indexOf(BEGIN);
  const end = source.indexOf(END);
  if (start === -1 || end === -1) throw new Error(`${site.dir}/site.js has no DEMO KEY markers`);

  const block = [
    BEGIN + ' — generated by scripts/keygen.mjs on ' + new Date().toISOString().slice(0, 10) + '.',
    '   DEMO ONLY. In a real deployment the private key never reaches the browser:',
    '   signing happens in a serverless function on this origin, and this file would',
    '   call it instead of holding the key. The public half is published at',
    '   /.well-known/baton/key.json so any other site can check our signatures. */',
    'const DEMO_PRIVATE_JWK = ' + JSON.stringify(privateJwk, null, 2).replace(/\n/g, '\n') + ';',
    END
  ].join('\n');

  writeFileSync(sitePath, source.slice(0, start) + block + source.slice(end + END.length));
  console.log(`${site.dir}: new key ${site.kid} → .well-known/baton/key.json + site.js`);
}
